modLoader = "kotlinforforge"
loaderVersion = "[5.9,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lostarcana"
version = "${version}"
displayName = "Lost Arcana"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.lostarcana]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lostarcana]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lostarcana]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "lostarcana.mixins.json"
